
// <auto-generated />
namespace AzCopy.Contract
{
    public class JobsResumeOption : CommandArgsBase
    {
        /// <summary>
		/// destination SAS token of the destination for a given Job ID.
        /// </summary>
		[CLIArgumentName("destination-sas", true)]
		public string DestinationSas { get; set; }

        /// <summary>
		/// Filter: exclude these failed transfer(s) when resuming the job. Files should be separated by ';'.
        /// </summary>
		[CLIArgumentName("exclude", true)]
		public string Exclude { get; set; }

        /// <summary>
		/// Filter: only include these failed transfer(s) when resuming the job. Files should be separated by ';'.
        /// </summary>
		[CLIArgumentName("include", true)]
		public string Include { get; set; }

        /// <summary>
		/// Source SAS token of the source for a given Job ID.
        /// </summary>
		[CLIArgumentName("source-sas", true)]
		public string SourceSas { get; set; }

        /// <summary>
		/// Caps the transfer rate, in megabits per second. Moment-by-moment throughput might vary slightly from the cap. If this option is set to zero, or it is omitted, the throughput isn't capped.
        /// </summary>
		[CLIArgumentName("cap-mbps")]
		public float? CapMbps { get; set; }

        /// <summary>
		/// Define the log verbosity for the log file, available levels: INFO(all requests/responses), WARNING(slow responses), ERROR(only failed requests), and NONE(no output logs). (default 'INFO'). (default "INFO")
        /// </summary>
		[CLIArgumentName("log-level", true)]
		public string LogLevel { get; set; }

        /// <summary>
		/// Define the output verbosity. Available levels: essential, quiet. (default "default")
        /// </summary>
		[CLIArgumentName("output-level", true)]
		public string OutputLevel { get; set; }

        /// <summary>
		/// Format of the command's output. The choices include: text, json. The default value is 'text'. (default "text")
        /// </summary>
		[CLIArgumentName("output-type", true)]
		public string OutputType { get; set; }

        /// <summary>
		/// Specifies additional domain suffixes where Azure Active Directory login tokens may be sent.  The default is '*.core.windows.net;*.core.chinacloudapi.cn;*.core.cloudapi.de;*.core.usgovcloudapi.net;*.storage.azure.net'. Any listed here are added to the default. For security, you should only put Microsoft Azure domains here. Separate multiple entries with semi-colons.
        /// </summary>
		[CLIArgumentName("trusted-microsoft-suffixes", true)]
		public string TrustedMicrosoftSuffixes { get; set; }

	}
}